services:

  urlshortener.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: urlshortener-database
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MyStrongPassword@123
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped
    networks:
      - application-network
        
  urlshortener.redis:
    image: redis:latest
    container_name: urlshortener-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - application-network
        
  urlshortener.seq:
    image: datalust/seq:latest
    container_name: urlshortener-seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=True
    ports:
      - "5341:80"
    volumes:
      - seq_data:/data
    restart: unless-stopped
    networks:
      - application-network


  urlshortener.api:
    build:
      context: .
      dockerfile: UrlShortener.API/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    container_name: urlshortener-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Default=Server=urlshortener.database,1433;Database=urlshortener-db;User Id=sa;Password=MyStrongPassword@123;Trusted_Connection=False;TrustServerCertificate=True;
      - ConnectionStrings__Redis=urlshortener.redis:6379
      - Serilog__WriteTo__1__Args__serverUrl=http://urlshortener.seq:5341
    depends_on:
      - urlshortener.database
      - urlshortener.redis
      - urlshortener.seq
    restart: unless-stopped
    networks:
      - application-network

volumes:
  sqlserver_data:
  seq_data:
    
networks:
  application-network:
    driver: bridge